ParasHQ/paras-landing

components/ActivityDetail.js, components/CardDetail.js, next.config.js, pages/[id].js, pages/activity.js, pages/activity/[id].js, pages/token/[id].js, utils/common.js
1. Shareable Activity
Allow users to share activity via link/twitter/facebook
Refactor ActivityLog & ActivityDetail
2. New Buy modal for non-authenticated users 
3. Add social card for profile page
=> Add Shareable Activity & Profile Page Meta

components/CardDetail.js
untuk stylingnya kepikirannya baru gini mas
=> Sort Ownership

components/CardDetail.js, components/FeaturedPost.js, components/Nav.js, package.json, pages/market.js
1. featured post
2. UI bug fix
=> Featured post and UI bug

components/FilterMarket.js, pages/market.js, pages/publication/[...slug].js, pages/search.js
1. sort by (market update, card update, lowest price, highest price)
2. filter by min price and max price
=> filter market

components/FilterMarket.js, components/ProfileEdit.js, components/TextEditor.js, components/TextEditorPlugin.js, package.json, pages/market.js, pages/publication/[...slug].js, pages/search.js, styles/tailwind.css, utils/common.js
- Add filter/sort on market
- Add filter/sort on search
- Add breadcrumb on publication
- Add embed video on publication
=> Add market filter/sort

components/AddCategoryModal.js, components/Bid.js, components/BidList.js, components/CategoryList.js, components/FilterActivity.js, components/Nav.js, pages/category-submission/[categoryId].js, pages/market/[categoryId].js, pages/market/all-category.js, pages/publication/[type]/[slug].js, store.js
- submit category
- manage submission category
=> Add category feature

.eslintrc, components/BidList.js, components/Card.js, components/CardDetail.js, components/TextEditorPlugin.js, package.json, pages/[id]/collection/[collectionName].js, pages/activity/[id].js, yarn.lock
=> add eslint

pages/market/[categoryId].js, store.js
=> fix category

components/CardDetail.js
add google analytics event on card detail
=> add ga event

components/Filter/FilterActivity.js
Add button to filter activity based on latest bidding by creating key filter in FilterActivity.js
[x] Chrome
[x] Edge
=> feat: add bid filter in activity

components/Filter/FilterMarket.js, pages/collection/[collection_id].js
No filter in collection page 
Using FilterMarket component in collection page and add props for displaying "Verified Only" checkbox, default to true.
[x] Chrome 95.0
[x] Edge 95.0
=> Feat: add filter in collection page

components/Notification/NotificationItem.js
Typing token.edition.id instead of token.edition_id on Minted notification condition
Change token.edition.id to token.edition_id
=> chore: typo token.edition_id

components/Filter/FilterMarket.js, pages/collection/[collection_id].js
- Change hook dependency into specific query string
- Spread operator in FilterMarket for is_verified query parameter
Encounter warning for elements having the same key attribute on localhost
=> fix: re-render after close modal

components/Common/form/components/InputSelect/InputSelect.js, components/Modal/ReportModal.js, components/Token/TokenDetail.js, components/TokenSeries/TokenSeriesDetail.js, content/locale/en.js, next.config.js
=> feat: report item

components/Collection/CollectionStats.js, content/locale/en.js
[x] Show Total Minted explicitly in Collection Stats
=> fix: total minted cards

pages/collection/[collection_id].js
[x] Add condition to show Filter Attribute button
=> fix: conditional filter attribute button

components/Nav.js, components/Publication/PublicationEditor.js, utils/common.js
fix: can not update old publication
=> fix: can not update old publication

components/Publication/PublicationEditor.js, utils/common.js
Reverts ParasHQ/paras-landing#228
=> Revert "fix: can not update old publication"

components/Modal/TokenSeriesMintModal.js
##Changes
[x] add toLocaleLowerCase in receiver id before mint
[x] https://nomicon.io/DataStructures/Account.html
=> fix: mint only lowercase receiverId

components/CategoryList.js, content/locale/config.js, content/locale/en.js, pages/categories.js
[x] Create new page that shows all token categories with lates token submitted into that category
=> feat: all categories page

components/Token/TokenList.js, components/TokenSeries/CardList.js
refactor: only show 4 loader card when scrolling
=> refactor: only show 4 loader card when scrolling

components/Tabs/TabOwners.js
[x] Fix oveflow for long token_id
=> fix: add overflow hidden

components/Activity/TopCollectorsAllTime.js, components/Collection/CollectionList.js, components/Collection/CollectionListLoader.js, components/Common/ArtistVerified.js, components/Modal/ChooseAccountModal.js, components/Modal/TokenSeriesUpdatePriceModal.js, components/Modal/TokenUpdatePriceModal.js, components/Profile/Profile.js, package.json, pages/[id]/collections.js, pages/activity.js, pages/collection/[collection_id].js, pages/event/[id].js, pages/market/[categoryId].js, pages/new.js, pages/search.js, yarn.lock
[x] collection search and profile
[x] top collectors all time
[x] add mime type
[x] add validation max price
[x] fix collection creator not showing
=> feat: collection search and profile, mime type, validation max

components/Collection/CollectionActivity.js, components/Common/Media.js, lib/store.js
feat: add video player in media
=> feat: add video player in media

pages/new.js
[x] Trim if attribute exist for every type and value
=> feat: trim attribute type value

components/Collection/CollectionActivity.js, content/locale/en.js
[x] Show no activity when collection has no activities
=> fix: empty collection activity

pages/search.js
[x] Add parameter to hide empty collections on search
=> feat: add param for empty collection on search

components/Notification/NotificationItem.js
Reverts ParasHQ/paras-landing#315
=> Revert "fix: offer"

components/Filter/FilterAttribute.js, components/Filter/FilterMarket.js, pages/collection/[collection_id].js, utils/common.js
=> feat: clear all new attributes

pages/collection/[collection_id].js
[x] Empty array if no card on collection
=> fix: no cards collection activity

pages/[id].js, pages/[id]/collectibles.js, pages/[id]/collections.js, pages/[id]/creation.js, pages/[id]/publication.js, pages/activity.js, pages/categories.js, pages/collection/edit/[collection_id].js, pages/drops.js, pages/event/[id].js, pages/faq.js, pages/index.js, pages/languages.js, pages/license.js, pages/login.js, pages/market.js, pages/market/[categoryId].js, pages/market/all-category.js, pages/my-bids.js, pages/new-collection.js, pages/new.js, pages/publication/create.js, pages/publication/edit/[pubId].js, pages/publication/index.js, pages/search.js, pages/verify/email/[id].js
Reverts ParasHQ/paras-landing#341
=> Revert "feat: SEO improvement"

components/Card/CardLoader.js, components/Modal/MarketTokenModal.js, components/Modal/PlaceBidModal.js, components/Modal/TokenBuyModal.js, components/Modal/TokenSeriesBuyModal.js, components/Token/TokenList.js, components/TokenSeries/CardList.js
=> feat: action (buy, offer, update) from card list

components/Collection/CollectionStats.js, components/Collection/CreateCollection.js, components/ImgCrop.js, components/Profile/ProfileEdit.js, pages/collection/[collection_id].js, pages/collection/edit/[collection_id].js
[x] cover collection
[x] flex collections stats
=> feat: cover profile collection

components/Card/CardListLoaderSmall.js, components/Filter/FilterDisplay.js, components/Token/TokenList.js, components/TokenSeries/CardList.js, pages/[id]/collectibles.js, pages/[id]/creation.js, pages/collection/[collection_id].js, pages/market.js
- toggle available in market, collections, collectibles, and creations
- CardList and TokenList
- 2 options (large and small display) (default large)
=> feat: toggle display

components/Card/CardListLoaderSmall.js, components/Filter/FilterDisplay.js, components/Token/TokenList.js, components/TokenSeries/CardList.js, pages/[id]/collectibles.js, pages/[id]/creation.js, pages/collection/[collection_id].js, pages/market.js
- key in map
- padding between card
- toggle color
- font size
=> refactor: some bugs

components/Card/CardListLoader.js, components/Profile/Profile.js
[x] mobile horizontal row
[x] touchup card loader creation
=> feat: mobile horizontal row on profile tab

components/Filter/FilterAttribute.js
[x] Show count trait on filter
=> fix: show count trait type

components/Card/Card.js, components/Common/Media.js, components/Token/TokenDetail.js, components/Token/TokenList.js, components/TokenSeries/CardList.js, components/TokenSeries/TokenSeriesDetail.js
available only on GIF type cards that already have mime_type attribute in metadata
=> feat: optimize imgix gif

components/Collection/CollectionActivity.js, components/LineChart/DailyVolume.js
[x] Add volume label on left side
=> hotfix: add volume label

components/Collection/CollectionList.js, pages/[id]/collections.js, pages/search.js
[x] Show collection stats on collection page (search and collection profile)
[x] Sort by volume on collection page (search and collection profile)
=> feat: collection sort

components/Collection/CollectionList.js, pages/[id]/collections.js, pages/search.js
This reverts commit 2b8e5db9d5e301cb043b666063b1cf28671c96bb.
=> Revert "feat: collection sort (#413)"

components/Collection/CollectionActivity.js, pages/collection/[collection_id].js
=> feat: sort collection activity

components/AutoComplete/AutoCompleteList.js, components/Common/ButtonScrollTop.js, components/Nav.js, components/Profile/Profile.js, pages/[id]/collectibles.js, pages/collection/[collection_id].js
[x] feat -> add search autocomplete
=> Issue 422 search autocomplete

components/AutoComplete/AutoCompleteList.js, components/Collection/CollectionActivity.js, components/Collection/CreateCollection.js, components/Common/ButtonScrollTop.js, components/Nav.js, components/Profile/Profile.js, components/Profile/ProfileEdit.js, pages/[id]/collectibles.js, pages/collection/[collection_id].js, pages/collection/edit/[collection_id].js, utils/common.js
[x] Search autocomplete
[x] Collection activity sort
[x] Validation socmed
=> Release 9 March

components/Tabs/TabInfo.js
[x] Show rarity score on token detail
=> feat: add rarity score on token detail

pages/new.js, pages/privacy.js, styles/privacy.module.css
=> Add privacy page and create card UI update

next.config.js, package.json, pages/artist-verification.js, yarn.lock
- form with recaptcha
Note : please use ReCaptcha v2
=> add recaptcha at form artist verification

components/Collection/CollectionStats.js, content/locale/en.js
[x] Show total nfts listed (on sale) on collection stats
[x] Wrap all collection stats on grid when XSmall size and flex-row when Medium or above
=> feat: show nfts listed

components/Home/HomeCardList.js, components/Token/TokenList.js
[x] Display 2 columns on small devices
[x] Using two different tags to handle only by html
=> fix: use display small small device

components/Activity/ActivityDetail.js, components/Collection/CollectionActivity.js, components/Collection/CollectionSearch.js, components/Collection/CollectionStats.js, components/Filter/FilterMarket.js, components/Icons/component/IconInfo.js, components/Modal/TokenSeriesUpdatePriceModal.js, components/Modal/TokenUpdatePriceModal.js, components/Tabs/TabHistory.js, components/Tabs/TabInfo.js, content/locale/en.js, content/locale/es.js, content/locale/ru.js, content/locale/zh.js, pages/artist-verification.js, pages/collection/[collection_id].js, pages/new.js
[x] Share for new verified artist
[x] Owned tab collection
[x] Tooltip collection stats
[x] Locked fee
[x] Search on collection
=> Release 21 April

components/Bid/Bid.js, components/Modal/AddTradeNFTUrlModal.js, components/Modal/BannedConfirmModal.js, components/Tabs/TabOffers.js, constants/flag.js, content/locale/en.js
[-] Disable trading using NFT from non-verified / flagged creator
[-] New scam flag
=> Release: Trade for verified NFTs only

components/Modal/SuccessTransactionModal.js, package.json, pages/new.js, yarn.lock
* fix: added async to category submit when card creation
* fix: added async in sender wallet
=> fix: added async to category submit when card creation (#591)

utils/common.js
supports QmTAJYnH9YfvtBGdHptFUpkbHZZs5hhqggySHr63VfNZQE/battlepass.png like path
=> feat: support CID as folder (ipfs://xxx/file.jpeg)

components/Card/Card.js, components/Tabs/TabAuction.js, components/TokenSeries/CardList.js
=> feat: integration UI

components/Tabs/TabAuction.js
Remove empty bidder_id on extended auction
=> fix remove empty bidder_id

content/locale/en.js, pages/my-bids.js
##Changes
[+] Rename "My Bids" into "My Offers"
=> fix: rename bids to offers

pages/[id]/collectibles.js, pages/[id]/creation.js, pages/collection/[collection_id].js, pages/market.js
- market
- collection page
- collectibles
- creation
=> fix: ended soonest sort pagination

pages/[id].js, pages/[id]/collectibles.js, pages/[id]/collections.js, pages/[id]/creation.js, pages/[id]/liked.js, pages/[id]/publication.js
[x] Remove the use of socialCard api and change it to profile image instead.
=> feat: remove social card api

components/Launchpad/LaunchpadStats.js
[x] Show warning on projects that does not contain tags = 'paras'
=> fix: show warning if non paras tag

.gitignore, components/Activity/ActivityDetail.js, components/Collection/CollectionStats.js, components/Filter/FilterAddCollection.js, components/Follow/ActivityUserFollow.js, components/Follow/ActivityUserFollow/ActivityDescriptionBottom.js, components/Follow/ActivityUserFollow/ActivityDescriptionCenter.js, components/Follow/ActivityUserFollow/ActivityDescriptionTop.js, components/Follow/ActivityUserFollow/ActivityFollowingBottom.js, components/Follow/ActivityUserFollow/ActivityFollowingTop.js, components/Launchpad/LaunchpadStats.js, components/Launchpad/ReminderCheckbox.js, components/Modal/LaunchpadRemindModal.js, components/Modal/SuccessTransactionModal.js, components/RecyclerScroll/RecyclerCommon.js, lib/store.js, package.json, pages/[id].js, pages/[id]/collectibles.js, pages/[id]/collections.js, pages/[id]/creation.js, pages/[id]/liked.js, pages/[id]/publication.js, pages/activity.js, pages/activity/[id].js, pages/mint-calendar/[launchpad_id]/project/[project_id].js, pages/new.js, styles/tailwind.css, yarn.lock
[x] Remove social card 
[x] Collection search in card
[x] Recycler scroll
[x] Activity page phase 2
[x] Collection stats to '-' when loading
[x] Launchpad email reminder
=> Release 4 August

components/User/User.js, lib/ga.js
* feat: nft lending integration with pawn protocol
* fix: update url
* fix: update link
=> feat: nft lending integration with pawn protocol (#867)

components/Bid/Bid.js, components/Common/WalletSelector.js, components/Modal/AcceptBidAuctionModal.js, components/Modal/CancelAuctionModal.js, components/Modal/CancelBidModal.js, components/Modal/LoginModal.js, components/Modal/PlaceOfferModal.js, components/Modal/SignMessageModal.js, components/Modal/TokenAuctionBidModal.js, components/Modal/TokenBurnModal.js, components/Modal/TokenBuyModal.js, components/Modal/TokenSeriesBurnModal.js, components/Modal/TokenSeriesBuyModal.js, components/Modal/TokenSeriesMintModal.js, components/Modal/TokenSeriesUpdatePriceModal.js, components/Modal/TokenTransferModal.js, components/Modal/TradeNFTModal.js, components/Tabs/TabCreateAuction.js, components/Tabs/TabOffers.js, components/Tabs/TabTokenUpdatePrice.js, components/TokenUtils/TokenOffers.js, components/User/User.js, package.json, pages/login.js, pages/new.js, yarn.lock
=> Release 6 Sept

components/Common/WalletSelector.js, components/Nav.js
Example: https://paras.id/?settings=newsletter
note: setting modal can be open only when user login
=> feat: add link for unsubscribe to newsletter

components/Common/WalletSelector.js
Reverts ParasHQ/paras-landing#940
=> Revert "hotfix: disable near wallet for login"

components/Modal/RaffleRewardModal.js, components/Notification/NotificationItem.js
new notif win raffle paras token
=> feat: add new notif win raffle paras token

components/Loyalty/LoyaltyMechanism.js, components/Nav.js, components/Notification/NotificationItem.js, pages/loyalty.js
[+] loyalty page 
[+] time period on notification
=> Release: 20 jan 2023

pages/category-submission/[categoryId]/index.js
This reverts commit a68e7d50547cc09186544bea1f4969e644857bac.
=> Revert "feat: adjust api res category submission (#1027)"
